version: '3.0'

services:
  frontend:
    hostname: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    hostname: backend
    build: ./backend
    ports:
      - "8080:8080"
